### ISSUE TITLE
Package content of 0.1.7 is empty on NPM

### ISSUE THREAD

**Issue by prinsss** [CodyJasonBennett/preact-reconciler#3]
Thanks for your great work on this package! I've been searching for solutions about replacing a react custom renderer which depends on `react-reconciler` with preact, and this package is truly a great inspiration.

However I've noticed that the [package content](https://www.npmjs.com/package/preact-reconciler/v/0.1.7?activeTab=code) on npm of version 0.1.7, which was released recently, did not contain any JavaScript codes. The version 0.1.6 has no such problem.

I'm wondering if this was a mistake during npm publishing? It would be appreciated if you could have a look at this. :)

```text
❯ curl -O -L https://registry.npmjs.org/preact-reconciler/-/preact-reconciler-0.1.7.tgz
❯ tar tvf preact-reconciler-0.1.7.tgz
drw-rw-rw-  0 0      0           0 Jul 19 21:02 package
-rw-rw-rw-  0 0      0        1069 Mar  5 03:05 package/LICENSE
-rw-rw-rw-  0 0      0        1894 Mar  6 08:01 package/README.md
-rw-rw-rw-  0 0      0        2024 Jul 19 21:03 package/package.json
```

**Comment by CodyJasonBennett** [comment]
Thanks. Released [v0.1.8](https://github.com/CodyJasonBennett/preact-reconciler/releases/tag/v0.1.8).
